--1. 
desc employees;
--2.
select * from employees;
--3.
select EMPLOYEE_ID, LAST_NAME, SALARY from employees;
--4.
SELECT LAST_NAME, FIRST_NAME, SALARY FROM EMPLOYEES
ORDER BY SALARY DESC;
--5.
SELECT EMPLOYEE_ID, JOB_ID, DEPARTMENT_ID FROM EMPLOYEES
WHERE JOB_ID = 'IT_PROG';
--6.
SELECT LAST_NAME, COMMISSION_PCT FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL
ORDER BY LAST_NAME ASC;
--7.

--8.
SELECT EMPLOYEE_ID AS "Emp#", LAST_NAME AS "Employee", JOB_ID AS "Job", HIRE_DATE AS "Hire Date" from EMPLOYEES;
--9.
SELECT LAST_NAME||','||JOB_ID AS "Employee and Title" FROM EMPLOYEES;
--10.
SELECT LAST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY >= 12000;
--11.
SELECT LAST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY BETWEEN 5000 AND 12000;
--12
SELECT LAST_NAME, JOB_ID, HIRE_DATE FROM EMPLOYEES
WHERE LAST_NAME IN('Matos', 'Taylor')
ORDER BY HIRE_DATE ASC;
--13
SELECT LAST_NAME, DEPARTMENT_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID IN('20', '50');
--14
SELECT LAST_NAME AS "Employee", SALARY AS "Monthly Salary" FROM EMPLOYEES
WHERE SALARY BETWEEN 5000 AND 12000
AND DEPARTMENT_ID IN('20','50');
--15
SELECT LAST_NAME, HIRE_DATE FROM EMPLOYEES
WHERE HIRE_DATE LIKE '04%';
--16
SELECT LAST_NAME, JOB_ID FROM EMPLOYEES
WHERE MANAGER_ID IS NULL;
--17
SELECT LAST_NAME, SALARY, COMMISSION_PCT FROM EMPLOYEES
WHERE COMMISSION_PCT IS NOT NULL
ORDER BY SALARY DESC, COMMISSION_PCT DESC;
--18
SELECT LAST_NAME FROM EMPLOYEES
WHERE LAST_NAME LIKE '__a%';
--19
SELECT LAST_NAME FROM EMPLOYEES
WHERE LAST_NAME LIKE '%a%'
AND LAST_NAME LIKE '%a%e%';
--20
SELECT LAST_NAME, JOB_ID, SALARY FROM EMPLOYEES
WHERE JOB_ID IN ('IT_PROG', 'SA_REP')
AND SALARY NOT IN('4800', '7500', '10000');
--21
SELECT LAST_NAME AS "Employee", SALARY AS "Monthly Salary", COMMISSION_PCT AS "Commission" FROM EMPLOYEES
WHERE DEPARTMENT_ID IN('20', '80')
AND COMMISSION_PCT = 0.2;