CREATE TABLE VISITOR(
    NAME VARCHAR2(18),
    WRITEDATE DATE,
    MEMO VARCHAR(180)
);

INSERT INTO VISITOR ( NAME, WRITEDATE, MEMO)
    VALUES ('현재시간', SYSDATE, NULL);
INSERT INTO VISITOR ( NAME, WRITEDATE, MEMO)
    VALUES (NULL, TO_DATE('17/12/25','RR/MM/DD'), NULL);  
INSERT INTO VISITOR ( NAME, WRITEDATE, MEMO)
    VALUES (NULL, TO_DATE('99/08/11','RR/MM/DD'), NULL);

CREATE TABLE MEMBER(
    M_ID VARCHAR2(12) PRIMARY KEY,
    M_PWD VARCHAR2(12) NOT NULL,
    NAME VARCHAR2(18) NOT NULL,
    JOINDATE DATE DEFAULT SYSDATE
);

CREATE TABLE NEWS(
    ID NUMBER(8) PRIMARY KEY,
    WRITER VARCHAR2(120),
    CONTENT VARCHAR2(900),
    WRITEDATE DATE,
    CNT NUMBER(8)
);

CREATE SEQUENCE NEWS_SEQ
    INCREMENT BY 1
    START WITH 1
    NOMAXVALUE
    NOMINVALUE
    NOCYCLE
    NOCACHE;

CREATE TABLE MEETING(
    ID NUMBER(8) PRIMARY KEY,
    NAME VARCHAR2(18),
    TITLE VARCHAR2(120),
    MEETINGDATE DATE
);
CREATE SEQUENCE MEETING_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE IMGTEST(
    NAME VARCHAR2(18),
    IMGCONTENT BLOB
);

