# Generated by Django 2.1.15 on 2020-06-27 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='lat',
            field=models.FloatField(default=37),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='lng',
            field=models.FloatField(default=127),
            preserve_default=False,
        ),
    ]
