# Generated by Django 3.0.7 on 2020-06-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField()),
                ('name', models.TextField()),
                ('page', models.IntegerField()),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
